# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
script:
- xctool test -workspace Example/Download-Font-iOS.xcworkspace -scheme Download-Font-iOS -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
